Stepping off the ferry, I walked the short distance to An Laimhrig, the pier centre. Recently expanded and redeveloped to better serve the increasing number of islanders and visitors, the complex is at the heart of community life. As I oriented myself with a map, islanders came and went, collecting deliveries, dropping off letters and buying supplies in the island's sole grocery shop that doubles as the post office, and sharing news in the cafe. As well as the cafe and grocery shop, the complex houses a craft shop, bike hire and a wash house that provides toilets and showers for those wild camping or staying in community-owned camping pods. It's also where the stone monument commemorating the 1997 community buyout of the island stands.

After a run of landlords who were either absent from the island or uninterested in its development, the residents of Eigg were convinced community ownership was the only way to guarantee the island's future. As Maggie Fyffe, secretary of the Isle of Eigg Heritage Trust (the organisation that owns the Isle of Eigg), told me, "The island realised that we weren't going to have much of a community unless we did it ourselves."

When the island came up for sale in 1996, locals began raising money. "The residents contributed, and we had a big fundraising campaign. But we had the famous mystery donor who gave us a million quid in the end, and that's what clinched it."

Although visitors come for many reasons, Eigg is best suited to those with an interest in the outdoors. Its most famous sights are the Singing Sands beach at the north of the island that squeaks and squeals as the quartz sand is disturbed, and the towering pitchstones ridge of An Sgurr, formed some 58 million years ago from a volcanic eruption that looms over the east of the island.

In between are rugged plains, moorland, woodland, miles of coastline and white-sand beaches that could have been lifted from the Caribbean, and even a small section of temperate rainforest. The island is largely untouched by the industries that have altered the countryside across much of Britain. "We don't have very intense farming or agriculture here," said Barnes. "The landscape is conducive to wildlife. There's no commercial fishing or large-scale farming and the coastal line, shore and beaches and sea are clean, clear waters."

To make the most of the clear sky and the view from its summit, I set out to climb An Sgurr. Looking at its face, it appeared unconquerable with towering walls of sheer black stone, but a path that curves around its back offered a relatively easy climb to the top. At nearly 400m, the views from the summit were incredible, extending out towards Rùm, Skye and the mainland. But nowhere offers a better panorama of Eigg itself, and as the wind picked up, my eyes were drawn down to where the island's wind turbines were churning the air.
